export const MAX_SNAPSHOT_BUFFER = 20
export const MIN_INTERP_DELAY_MS = 60
export const MAX_EXTRAPOLATION_MS = 70

export const OFFSET_SMOOTHING = 0.12
export const CAMERA_DISTANCE_DEFAULT = 5.2
export const CAMERA_DISTANCE_MIN = 4.2
export const CAMERA_DISTANCE_MAX = 9
export const CAMERA_ZOOM_SENSITIVITY = 0.0015
export const POINTER_MAX_RANGE_RATIO = 0.25
export const CAMERA_FOV_DEGREES = 40
export const PLANET_RADIUS = 3
export const VIEW_RADIUS_EXTRA_MARGIN = 0.08

export const BOOST_EFFECT_FADE_IN_RATE = 9
export const BOOST_EFFECT_FADE_OUT_RATE = 12
export const BOOST_EFFECT_PULSE_SPEED = 8.5
export const BOOST_EFFECT_ACTIVE_CLASS_THRESHOLD = 0.01

export const SCORE_RADIAL_FADE_IN_RATE = 10
export const SCORE_RADIAL_FADE_OUT_RATE = 8
export const SCORE_RADIAL_INTERVAL_SMOOTH_RATE = 14
export const SCORE_RADIAL_MIN_CAP_RESERVE = 1e-6
export const SCORE_RADIAL_BLOCKED_FLASH_MS = 320

export const MENU_CAMERA_DISTANCE = 7
export const MENU_CAMERA_VERTICAL_OFFSET = 2.5
export const MENU_TO_GAMEPLAY_BLEND_MS = 900
export const MENU_OVERLAY_FADE_OUT_MS = 220
export const DEATH_TO_MENU_DELAY_MS = 3000

export const REALTIME_LEADERBOARD_LIMIT = 5
